### ISSUE TITLE
create contact error

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.grantprograms#262]
When trying to create a contact on create grant form popup, after filling in 3 fields and submitting received:

DB Error: constraint violation
Error Details
Database Error Code: Cannot add or update a child row: a foreign key constraint fails (`gp_civicrm`.`civicrm_log`, CONSTRAINT `FK_civicrm_log_modified_id` FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE), 1452
Additional Details:
Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -3
    [message] => DB Error: constraint violation
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modified_date ) VALUES ('civicrm_contact' ,  204 , 'civicrm_contact,204' ,  214 ,  20180514192510 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`gp_civicrm`.`civicrm_log`, CONSTRAINT `FK_civicrm_log_modified_id` FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modified_date ) VALUES ('civicrm_contact' ,  204 , 'civicrm_contact,204' ,  214 ,  20180514192510 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`gp_civicrm`.`civicrm_log`, CONSTRAINT `FK_civicrm_log_modified_id` FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]
    [to_string] => [db_error: message="DB Error: constraint violation" code=-3 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modified_date ) VALUES ('civicrm_contact' ,  204 , 'civicrm_contact,204' ,  214 ,  20180514192510 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`gp_civicrm`.`civicrm_log`, CONSTRAINT `FK_civicrm_log_modified_id` FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]"]
)

**Comment by JoeMurray** [comment]
backTrace

#0 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Error.php(149): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB.php(969): PEAR_Error->PEAR_Error("DB Error: constraint violation", -3, 16, (Array:2), "INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...")
#4 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-3, 16, (Array:2), "INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...")
#5 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -3, NULL, NULL, "INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...", "DB_Error", TRUE)
#6 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/mysql.php(898): DB_common->raiseError(-3, NULL, NULL, NULL, "1452 ** Cannot add or update a child row: a foreign key constraint fails (`gp...")
#7 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/mysql.php(327): DB_mysql->mysqlRaiseError()
#8 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...")
#9 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(2434): DB_common->query("INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...")
#10 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/DB/DataObject.php(1055): DB_DataObject->_query("INSERT INTO civicrm_log (entity_table , entity_id , data , modified_id , modi...")
#11 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/DAO.php(278): DB_DataObject->insert()
#12 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/BAO/Log.php(119): CRM_Core_DAO->save()
#13 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(223): CRM_Core_BAO_Log::register(204, "civicrm_contact", 204)
#14 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(313): CRM_Contact_BAO_Contact::add((Array:13))
#15 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(1779): CRM_Contact_BAO_Contact::create((Array:13))
#16 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Profile/Form.php(1283): CRM_Contact_BAO_Contact::createProfileContact((Array:9), (Array:3), NULL, NULL, "4", NULL, TRUE)
#17 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Profile/Form/Edit.php(293): CRM_Profile_Form->postProcess()
#18 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Form.php(261): CRM_Profile_Form_Edit->postProcess()
#19 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#20 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Profile_Form_Edit), "next", "Next")
#21 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Profile_Form_Edit), "next")
#22 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Profile_Form_Edit), "next")
#23 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Controller.php(339): HTML_QuickForm_Page->handle("next")
#24 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(117): CRM_Core_Controller->run()
#25 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(443): CRM_Utils_Wrapper->run("CRM_Profile_Form_Edit", "Create Profile", (Array:2))
#26 [internal function](): CRM_Core_Invoke::profile((Array:3))
#27 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(293): call_user_func((Array:2), (Array:3))
#28 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(76): CRM_Core_Invoke::runItem((Array:14))
#29 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#30 /home/grantprograms.jmaconsulting.biz/htdocs/sites/all/modules/civicrm/drupal/civicrm.module(484): CRM_Core_Invoke::invoke((Array:3))
#31 [internal function](): civicrm_invoke("profile", "create")
#32 /home/grantprograms.jmaconsulting.biz/htdocs/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#33 /home/grantprograms.jmaconsulting.biz/htdocs/index.php(21): menu_execute_active_handler()
#34 {main}
